### ISSUE TITLE
Broken doc links

### ISSUE THREAD

**Issue by jorloplaz** [iiconocimiento/aisee#7]
The links belonging to the `Getting Started` and `Contributing` sections appear to be broken.

For instance, when clicking on [AISee Documentation](https://aisee.readthedocs.io/), the following is shown:

![image](https://user-images.githubusercontent.com/12827365/234211587-4c3eee5b-0e51-4cd1-b960-607c3b0055b3.png)

**Comment by GuillemGSubies** [comment]
Those were just placeholders until the real documentation is live. It should be ready today, you can see the progress here #5  

The main branch documentation is already live here:

https://iiconocimiento.github.io/aisee/dev/

**Comment by GuillemGSubies** [comment]
Closing, everything is merged and working
